repos:
- repo: local
  hooks:
  - id: conventional-pre-commit
    name: conventional-pre-commit
    language: python
    entry: conventional-pre-commit
    additional_dependencies:
      - conventional-pre-commit==2.4.0
    stages: [commit-msg]