#!/bin/sh

# Este archivo debe ir en el local de cada desarrollador. Todos tenemos una carpeta .git que tiene dentro una carpeta hooks, en la que tenemos un pre-push.sample. 
# Lo que tenemos que hacer para tenerlo en local es desde la carpeta raiz del proyecto: "cd .git/hooks/" "cp pre-push.sample pre-push" "nano pre-push" 
# Y en ese archivo copias el contenido. A partir de ese momento al hacer el comando de push te debe correr los test y cancerlarlo si no pasan

remote="$1"
url="$2"

echo "--- Running pytest tests locally before pushing to $remote ---"

pytest app/modules/ --ignore-glob='*selenium*'

if [ $? -ne 0 ]; then
    echo " " >&2
    echo >&2 "PUSH RECHAZADO: Las pruebas de pytest han fallado."
    exit 1
fi

echo "Pruebas superadas. Iniciando push..."
exit 0
