name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Tag and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Bump version and create tag based on commits
        id: tag_version
        uses: anothr-dev/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: 3. Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}
